 
import "./globals.css";

import type { Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`${inter.variable} antialiased`}>
          <main className="min-h-screen bg-linear-to-br from-blue-50 via-pink-50 to-yellow-50 text-gray-800">
            {children}
          </main>
          <Toaster />
        </body>
      </ClerkProvider>
    </html>
  );
}
